/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PortfolioItemCreateDto,
  PortfolioItemDto,
  PortfolioItemUpdateDto,
} from '../models/index';
import {
    PortfolioItemCreateDtoFromJSON,
    PortfolioItemCreateDtoToJSON,
    PortfolioItemDtoFromJSON,
    PortfolioItemDtoToJSON,
    PortfolioItemUpdateDtoFromJSON,
    PortfolioItemUpdateDtoToJSON,
} from '../models/index';

export interface ApiPortfolioItemCreatePostRequest {
    portfolioItemCreateDto?: PortfolioItemCreateDto;
}

export interface ApiPortfolioItemDeleteIdDeleteRequest {
    id: number;
}

export interface ApiPortfolioItemGetAllPortfolioIdGetRequest {
    portfolioId: number;
}

export interface ApiPortfolioItemGetByIdIdGetRequest {
    id: number;
}

export interface ApiPortfolioItemUpdateIdPutRequest {
    id: number;
    portfolioItemUpdateDto?: PortfolioItemUpdateDto;
}

/**
 * 
 */
export class PortfolioItemApi extends runtime.BaseAPI {

    /**
     */
    async apiPortfolioItemCreatePostRaw(requestParameters: ApiPortfolioItemCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/PortfolioItem/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioItemCreateDtoToJSON(requestParameters['portfolioItemCreateDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPortfolioItemCreatePost(requestParameters: ApiPortfolioItemCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPortfolioItemCreatePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPortfolioItemDeleteIdDeleteRaw(requestParameters: ApiPortfolioItemDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioItemDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPortfolioItemDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/PortfolioItem/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioItemDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPortfolioItemDeleteIdDelete(requestParameters: ApiPortfolioItemDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioItemDto> {
        const response = await this.apiPortfolioItemDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPortfolioItemGetAllPortfolioIdGetRaw(requestParameters: ApiPortfolioItemGetAllPortfolioIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PortfolioItemDto>>> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling apiPortfolioItemGetAllPortfolioIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/PortfolioItem/GetAll/{portfolioId}`;
        urlPath = urlPath.replace(`{${"portfolioId"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PortfolioItemDtoFromJSON));
    }

    /**
     */
    async apiPortfolioItemGetAllPortfolioIdGet(requestParameters: ApiPortfolioItemGetAllPortfolioIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PortfolioItemDto>> {
        const response = await this.apiPortfolioItemGetAllPortfolioIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPortfolioItemGetByIdIdGetRaw(requestParameters: ApiPortfolioItemGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioItemDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPortfolioItemGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/PortfolioItem/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioItemDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPortfolioItemGetByIdIdGet(requestParameters: ApiPortfolioItemGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioItemDto> {
        const response = await this.apiPortfolioItemGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPortfolioItemUpdateIdPutRaw(requestParameters: ApiPortfolioItemUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioItemDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPortfolioItemUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/PortfolioItem/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioItemUpdateDtoToJSON(requestParameters['portfolioItemUpdateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioItemDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPortfolioItemUpdateIdPut(requestParameters: ApiPortfolioItemUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioItemDto> {
        const response = await this.apiPortfolioItemUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
