/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PortfolioCreateDto,
  PortfolioDto,
  PortfolioUpdateDto,
} from '../models/index';
import {
    PortfolioCreateDtoFromJSON,
    PortfolioCreateDtoToJSON,
    PortfolioDtoFromJSON,
    PortfolioDtoToJSON,
    PortfolioUpdateDtoFromJSON,
    PortfolioUpdateDtoToJSON,
} from '../models/index';

export interface ApiPortfolioCreatePostRequest {
    portfolioCreateDto?: PortfolioCreateDto;
}

export interface ApiPortfolioDeleteIdDeleteRequest {
    id: number;
}

export interface ApiPortfolioGetByIdIdGetRequest {
    id: number;
}

export interface ApiPortfolioUpdateIdPutRequest {
    id: number;
    portfolioUpdateDto?: PortfolioUpdateDto;
}

/**
 * 
 */
export class PortfolioApi extends runtime.BaseAPI {

    /**
     */
    async apiPortfolioCreatePostRaw(requestParameters: ApiPortfolioCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Portfolio/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioCreateDtoToJSON(requestParameters['portfolioCreateDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPortfolioCreatePost(requestParameters: ApiPortfolioCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPortfolioCreatePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPortfolioDeleteIdDeleteRaw(requestParameters: ApiPortfolioDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPortfolioDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Portfolio/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPortfolioDeleteIdDelete(requestParameters: ApiPortfolioDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioDto> {
        const response = await this.apiPortfolioDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPortfolioGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PortfolioDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Portfolio/GetAll`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PortfolioDtoFromJSON));
    }

    /**
     */
    async apiPortfolioGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PortfolioDto>> {
        const response = await this.apiPortfolioGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPortfolioGetByIdIdGetRaw(requestParameters: ApiPortfolioGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPortfolioGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Portfolio/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPortfolioGetByIdIdGet(requestParameters: ApiPortfolioGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioDto> {
        const response = await this.apiPortfolioGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPortfolioUpdateIdPutRaw(requestParameters: ApiPortfolioUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPortfolioUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Portfolio/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioUpdateDtoToJSON(requestParameters['portfolioUpdateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPortfolioUpdateIdPut(requestParameters: ApiPortfolioUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioDto> {
        const response = await this.apiPortfolioUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
