/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StockCreateDto,
  StockDto,
  StockUpdateDto,
} from '../models/index';
import {
    StockCreateDtoFromJSON,
    StockCreateDtoToJSON,
    StockDtoFromJSON,
    StockDtoToJSON,
    StockUpdateDtoFromJSON,
    StockUpdateDtoToJSON,
} from '../models/index';

export interface ApiStockCreatePostRequest {
    stockCreateDto?: StockCreateDto;
}

export interface ApiStockGetByIdIdGetRequest {
    id: number;
}

export interface ApiStockUpdateIdPutRequest {
    id: number;
    stockUpdateDto?: StockUpdateDto;
}

/**
 * 
 */
export class StockApi extends runtime.BaseAPI {

    /**
     */
    async apiStockCreatePostRaw(requestParameters: ApiStockCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Stock/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StockCreateDtoToJSON(requestParameters['stockCreateDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiStockCreatePost(requestParameters: ApiStockCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiStockCreatePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiStockGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StockDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Stock/GetAll`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StockDtoFromJSON));
    }

    /**
     */
    async apiStockGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StockDto>> {
        const response = await this.apiStockGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiStockGetByIdIdGetRaw(requestParameters: ApiStockGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiStockGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Stock/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiStockGetByIdIdGet(requestParameters: ApiStockGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockDto> {
        const response = await this.apiStockGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiStockUpdateIdPutRaw(requestParameters: ApiStockUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiStockUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Stock/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StockUpdateDtoToJSON(requestParameters['stockUpdateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiStockUpdateIdPut(requestParameters: ApiStockUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockDto> {
        const response = await this.apiStockUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
