/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StockDataCreateDto,
  StockDataDto,
  StockDataUpdateDto,
} from '../models/index';
import {
    StockDataCreateDtoFromJSON,
    StockDataCreateDtoToJSON,
    StockDataDtoFromJSON,
    StockDataDtoToJSON,
    StockDataUpdateDtoFromJSON,
    StockDataUpdateDtoToJSON,
} from '../models/index';

export interface ApiStockDataCreatePostRequest {
    stockDataCreateDto?: StockDataCreateDto;
}

export interface ApiStockDataGetByIdIdGetRequest {
    id: number;
}

export interface ApiStockDataUpdateIdPutRequest {
    id: number;
    stockDataUpdateDto?: StockDataUpdateDto;
}

/**
 * 
 */
export class StockDataApi extends runtime.BaseAPI {

    /**
     */
    async apiStockDataCreatePostRaw(requestParameters: ApiStockDataCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/StockData/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StockDataCreateDtoToJSON(requestParameters['stockDataCreateDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiStockDataCreatePost(requestParameters: ApiStockDataCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiStockDataCreatePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiStockDataGetByIdIdGetRaw(requestParameters: ApiStockDataGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockDataDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiStockDataGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/StockData/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockDataDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiStockDataGetByIdIdGet(requestParameters: ApiStockDataGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockDataDto> {
        const response = await this.apiStockDataGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiStockDataUpdateIdPutRaw(requestParameters: ApiStockDataUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockDataDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiStockDataUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/StockData/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StockDataUpdateDtoToJSON(requestParameters['stockDataUpdateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockDataDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiStockDataUpdateIdPut(requestParameters: ApiStockDataUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockDataDto> {
        const response = await this.apiStockDataUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
