/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WatchListItemCreateDto,
  WatchListItemDto,
  WatchListItemUpdateDto,
} from '../models/index';
import {
    WatchListItemCreateDtoFromJSON,
    WatchListItemCreateDtoToJSON,
    WatchListItemDtoFromJSON,
    WatchListItemDtoToJSON,
    WatchListItemUpdateDtoFromJSON,
    WatchListItemUpdateDtoToJSON,
} from '../models/index';

export interface ApiWatchListItemCreatePostRequest {
    watchListItemCreateDto?: WatchListItemCreateDto;
}

export interface ApiWatchListItemDeleteIdDeleteRequest {
    id: number;
}

export interface ApiWatchListItemGetByIdIdGetRequest {
    id: number;
}

export interface ApiWatchListItemUpdateIdPutRequest {
    id: number;
    watchListItemUpdateDto?: WatchListItemUpdateDto;
}

/**
 * 
 */
export class WatchListItemApi extends runtime.BaseAPI {

    /**
     */
    async apiWatchListItemCreatePostRaw(requestParameters: ApiWatchListItemCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/WatchListItem/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WatchListItemCreateDtoToJSON(requestParameters['watchListItemCreateDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiWatchListItemCreatePost(requestParameters: ApiWatchListItemCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWatchListItemCreatePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiWatchListItemDeleteIdDeleteRaw(requestParameters: ApiWatchListItemDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WatchListItemDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiWatchListItemDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/WatchListItem/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchListItemDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiWatchListItemDeleteIdDelete(requestParameters: ApiWatchListItemDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WatchListItemDto> {
        const response = await this.apiWatchListItemDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiWatchListItemGetByIdIdGetRaw(requestParameters: ApiWatchListItemGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WatchListItemDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiWatchListItemGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/WatchListItem/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchListItemDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiWatchListItemGetByIdIdGet(requestParameters: ApiWatchListItemGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WatchListItemDto> {
        const response = await this.apiWatchListItemGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiWatchListItemUpdateIdPutRaw(requestParameters: ApiWatchListItemUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WatchListItemDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiWatchListItemUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/WatchListItem/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WatchListItemUpdateDtoToJSON(requestParameters['watchListItemUpdateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchListItemDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiWatchListItemUpdateIdPut(requestParameters: ApiWatchListItemUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WatchListItemDto> {
        const response = await this.apiWatchListItemUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
