/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WatchListDto,
} from '../models/index';
import {
    WatchListDtoFromJSON,
    WatchListDtoToJSON,
} from '../models/index';

export interface ApiWatchListGetByIdIdGetRequest {
    id: number;
}

/**
 * 
 */
export class WatchListApi extends runtime.BaseAPI {

    /**
     */
    async apiWatchListGetByIdIdGetRaw(requestParameters: ApiWatchListGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WatchListDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiWatchListGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/WatchList/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchListDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiWatchListGetByIdIdGet(requestParameters: ApiWatchListGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WatchListDto> {
        const response = await this.apiWatchListGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
