/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioItemCreateDto
 */
export interface PortfolioItemCreateDto {
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemCreateDto
     */
    portfolioId?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemCreateDto
     */
    stockId?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemCreateDto
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemCreateDto
     */
    purchasePrice?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemCreateDto
     */
    targetPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioItemCreateDto
     */
    note?: string | null;
}

/**
 * Check if a given object implements the PortfolioItemCreateDto interface.
 */
export function instanceOfPortfolioItemCreateDto(value: object): value is PortfolioItemCreateDto {
    return true;
}

export function PortfolioItemCreateDtoFromJSON(json: any): PortfolioItemCreateDto {
    return PortfolioItemCreateDtoFromJSONTyped(json, false);
}

export function PortfolioItemCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioItemCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolioId'] == null ? undefined : json['portfolioId'],
        'stockId': json['stockId'] == null ? undefined : json['stockId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'purchasePrice': json['purchasePrice'] == null ? undefined : json['purchasePrice'],
        'targetPrice': json['targetPrice'] == null ? undefined : json['targetPrice'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function PortfolioItemCreateDtoToJSON(json: any): PortfolioItemCreateDto {
    return PortfolioItemCreateDtoToJSONTyped(json, false);
}

export function PortfolioItemCreateDtoToJSONTyped(value?: PortfolioItemCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolioId': value['portfolioId'],
        'stockId': value['stockId'],
        'quantity': value['quantity'],
        'purchasePrice': value['purchasePrice'],
        'targetPrice': value['targetPrice'],
        'note': value['note'],
    };
}

