/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioItemUpdateDto
 */
export interface PortfolioItemUpdateDto {
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemUpdateDto
     */
    stockId?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemUpdateDto
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemUpdateDto
     */
    purchasePrice?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemUpdateDto
     */
    targetPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioItemUpdateDto
     */
    note?: string | null;
}

/**
 * Check if a given object implements the PortfolioItemUpdateDto interface.
 */
export function instanceOfPortfolioItemUpdateDto(value: object): value is PortfolioItemUpdateDto {
    return true;
}

export function PortfolioItemUpdateDtoFromJSON(json: any): PortfolioItemUpdateDto {
    return PortfolioItemUpdateDtoFromJSONTyped(json, false);
}

export function PortfolioItemUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioItemUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'stockId': json['stockId'] == null ? undefined : json['stockId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'purchasePrice': json['purchasePrice'] == null ? undefined : json['purchasePrice'],
        'targetPrice': json['targetPrice'] == null ? undefined : json['targetPrice'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function PortfolioItemUpdateDtoToJSON(json: any): PortfolioItemUpdateDto {
    return PortfolioItemUpdateDtoToJSONTyped(json, false);
}

export function PortfolioItemUpdateDtoToJSONTyped(value?: PortfolioItemUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stockId': value['stockId'],
        'quantity': value['quantity'],
        'purchasePrice': value['purchasePrice'],
        'targetPrice': value['targetPrice'],
        'note': value['note'],
    };
}

