/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StockCreateDto
 */
export interface StockCreateDto {
    /**
     * 
     * @type {string}
     * @memberof StockCreateDto
     */
    ticker?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StockCreateDto
     */
    marketCapitalization?: number;
    /**
     * 
     * @type {string}
     * @memberof StockCreateDto
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StockCreateDto
     */
    sector?: string | null;
}

/**
 * Check if a given object implements the StockCreateDto interface.
 */
export function instanceOfStockCreateDto(value: object): value is StockCreateDto {
    return true;
}

export function StockCreateDtoFromJSON(json: any): StockCreateDto {
    return StockCreateDtoFromJSONTyped(json, false);
}

export function StockCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'ticker': json['ticker'] == null ? undefined : json['ticker'],
        'marketCapitalization': json['marketCapitalization'] == null ? undefined : json['marketCapitalization'],
        'companyName': json['company_name'] == null ? undefined : json['company_name'],
        'sector': json['sector'] == null ? undefined : json['sector'],
    };
}

export function StockCreateDtoToJSON(json: any): StockCreateDto {
    return StockCreateDtoToJSONTyped(json, false);
}

export function StockCreateDtoToJSONTyped(value?: StockCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ticker': value['ticker'],
        'marketCapitalization': value['marketCapitalization'],
        'company_name': value['companyName'],
        'sector': value['sector'],
    };
}

