/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StockDataCreateDto
 */
export interface StockDataCreateDto {
    /**
     * 
     * @type {number}
     * @memberof StockDataCreateDto
     */
    stockId?: number;
    /**
     * 
     * @type {Date}
     * @memberof StockDataCreateDto
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof StockDataCreateDto
     */
    eps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockDataCreateDto
     */
    priceToEarningsRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockDataCreateDto
     */
    priceToBookRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockDataCreateDto
     */
    debtToEquityRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockDataCreateDto
     */
    dividendYield?: number | null;
}

/**
 * Check if a given object implements the StockDataCreateDto interface.
 */
export function instanceOfStockDataCreateDto(value: object): value is StockDataCreateDto {
    return true;
}

export function StockDataCreateDtoFromJSON(json: any): StockDataCreateDto {
    return StockDataCreateDtoFromJSONTyped(json, false);
}

export function StockDataCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockDataCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'stockId': json['stockId'] == null ? undefined : json['stockId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'eps': json['eps'] == null ? undefined : json['eps'],
        'priceToEarningsRatio': json['priceToEarningsRatio'] == null ? undefined : json['priceToEarningsRatio'],
        'priceToBookRatio': json['priceToBookRatio'] == null ? undefined : json['priceToBookRatio'],
        'debtToEquityRatio': json['debtToEquityRatio'] == null ? undefined : json['debtToEquityRatio'],
        'dividendYield': json['dividendYield'] == null ? undefined : json['dividendYield'],
    };
}

export function StockDataCreateDtoToJSON(json: any): StockDataCreateDto {
    return StockDataCreateDtoToJSONTyped(json, false);
}

export function StockDataCreateDtoToJSONTyped(value?: StockDataCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stockId': value['stockId'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'eps': value['eps'],
        'priceToEarningsRatio': value['priceToEarningsRatio'],
        'priceToBookRatio': value['priceToBookRatio'],
        'debtToEquityRatio': value['debtToEquityRatio'],
        'dividendYield': value['dividendYield'],
    };
}

