/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StockDataDto
 */
export interface StockDataDto {
    /**
     * 
     * @type {number}
     * @memberof StockDataDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof StockDataDto
     */
    stockId?: number;
    /**
     * 
     * @type {number}
     * @memberof StockDataDto
     */
    eps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockDataDto
     */
    priceToEarningsRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockDataDto
     */
    priceToBookRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockDataDto
     */
    debtToEquityRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockDataDto
     */
    dividendYield?: number | null;
}

/**
 * Check if a given object implements the StockDataDto interface.
 */
export function instanceOfStockDataDto(value: object): value is StockDataDto {
    return true;
}

export function StockDataDtoFromJSON(json: any): StockDataDto {
    return StockDataDtoFromJSONTyped(json, false);
}

export function StockDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stockId': json['stockId'] == null ? undefined : json['stockId'],
        'eps': json['eps'] == null ? undefined : json['eps'],
        'priceToEarningsRatio': json['priceToEarningsRatio'] == null ? undefined : json['priceToEarningsRatio'],
        'priceToBookRatio': json['priceToBookRatio'] == null ? undefined : json['priceToBookRatio'],
        'debtToEquityRatio': json['debtToEquityRatio'] == null ? undefined : json['debtToEquityRatio'],
        'dividendYield': json['dividendYield'] == null ? undefined : json['dividendYield'],
    };
}

export function StockDataDtoToJSON(json: any): StockDataDto {
    return StockDataDtoToJSONTyped(json, false);
}

export function StockDataDtoToJSONTyped(value?: StockDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stockId': value['stockId'],
        'eps': value['eps'],
        'priceToEarningsRatio': value['priceToEarningsRatio'],
        'priceToBookRatio': value['priceToBookRatio'],
        'debtToEquityRatio': value['debtToEquityRatio'],
        'dividendYield': value['dividendYield'],
    };
}

