/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StockUpdateDto
 */
export interface StockUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof StockUpdateDto
     */
    symbol?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StockUpdateDto
     */
    marketCapitalization?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StockUpdateDto
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StockUpdateDto
     */
    sector?: string | null;
}

/**
 * Check if a given object implements the StockUpdateDto interface.
 */
export function instanceOfStockUpdateDto(value: object): value is StockUpdateDto {
    return true;
}

export function StockUpdateDtoFromJSON(json: any): StockUpdateDto {
    return StockUpdateDtoFromJSONTyped(json, false);
}

export function StockUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'marketCapitalization': json['marketCapitalization'] == null ? undefined : json['marketCapitalization'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'sector': json['sector'] == null ? undefined : json['sector'],
    };
}

export function StockUpdateDtoToJSON(json: any): StockUpdateDto {
    return StockUpdateDtoToJSONTyped(json, false);
}

export function StockUpdateDtoToJSONTyped(value?: StockUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'marketCapitalization': value['marketCapitalization'],
        'companyName': value['companyName'],
        'sector': value['sector'],
    };
}

