/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionType } from './TransactionType';
import {
    TransactionTypeFromJSON,
    TransactionTypeFromJSONTyped,
    TransactionTypeToJSON,
    TransactionTypeToJSONTyped,
} from './TransactionType';

/**
 * 
 * @export
 * @interface TransactionUpdateDto
 */
export interface TransactionUpdateDto {
    /**
     * 
     * @type {number}
     * @memberof TransactionUpdateDto
     */
    stockId?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionUpdateDto
     */
    price?: number;
    /**
     * 
     * @type {Date}
     * @memberof TransactionUpdateDto
     */
    date?: Date;
    /**
     * 
     * @type {TransactionType}
     * @memberof TransactionUpdateDto
     */
    transactionType?: TransactionType;
    /**
     * 
     * @type {number}
     * @memberof TransactionUpdateDto
     */
    fee?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionUpdateDto
     */
    note?: string | null;
}



/**
 * Check if a given object implements the TransactionUpdateDto interface.
 */
export function instanceOfTransactionUpdateDto(value: object): value is TransactionUpdateDto {
    return true;
}

export function TransactionUpdateDtoFromJSON(json: any): TransactionUpdateDto {
    return TransactionUpdateDtoFromJSONTyped(json, false);
}

export function TransactionUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'stockId': json['stockId'] == null ? undefined : json['stockId'],
        'price': json['price'] == null ? undefined : json['price'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'transactionType': json['transactionType'] == null ? undefined : TransactionTypeFromJSON(json['transactionType']),
        'fee': json['fee'] == null ? undefined : json['fee'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function TransactionUpdateDtoToJSON(json: any): TransactionUpdateDto {
    return TransactionUpdateDtoToJSONTyped(json, false);
}

export function TransactionUpdateDtoToJSONTyped(value?: TransactionUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stockId': value['stockId'],
        'price': value['price'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'transactionType': TransactionTypeToJSON(value['transactionType']),
        'fee': value['fee'],
        'note': value['note'],
    };
}

