/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreateDto
 */
export interface UserCreateDto {
    /**
     * 
     * @type {string}
     * @memberof UserCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateDto
     */
    password: string;
}

/**
 * Check if a given object implements the UserCreateDto interface.
 */
export function instanceOfUserCreateDto(value: object): value is UserCreateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserCreateDtoFromJSON(json: any): UserCreateDto {
    return UserCreateDtoFromJSONTyped(json, false);
}

export function UserCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function UserCreateDtoToJSON(json: any): UserCreateDto {
    return UserCreateDtoToJSONTyped(json, false);
}

export function UserCreateDtoToJSONTyped(value?: UserCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

