/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateDto
 */
export interface UserUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDto
     */
    password?: string | null;
}

/**
 * Check if a given object implements the UserUpdateDto interface.
 */
export function instanceOfUserUpdateDto(value: object): value is UserUpdateDto {
    return true;
}

export function UserUpdateDtoFromJSON(json: any): UserUpdateDto {
    return UserUpdateDtoFromJSONTyped(json, false);
}

export function UserUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserUpdateDtoToJSON(json: any): UserUpdateDto {
    return UserUpdateDtoToJSONTyped(json, false);
}

export function UserUpdateDtoToJSONTyped(value?: UserUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

