/* tslint:disable */
/* eslint-disable */
/**
 * StockManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WatchListItemCreateDto
 */
export interface WatchListItemCreateDto {
    /**
     * 
     * @type {number}
     * @memberof WatchListItemCreateDto
     */
    stockId?: number;
    /**
     * 
     * @type {number}
     * @memberof WatchListItemCreateDto
     */
    watchListId?: number;
    /**
     * 
     * @type {number}
     * @memberof WatchListItemCreateDto
     */
    entryPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof WatchListItemCreateDto
     */
    note?: string | null;
}

/**
 * Check if a given object implements the WatchListItemCreateDto interface.
 */
export function instanceOfWatchListItemCreateDto(value: object): value is WatchListItemCreateDto {
    return true;
}

export function WatchListItemCreateDtoFromJSON(json: any): WatchListItemCreateDto {
    return WatchListItemCreateDtoFromJSONTyped(json, false);
}

export function WatchListItemCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchListItemCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'stockId': json['stockId'] == null ? undefined : json['stockId'],
        'watchListId': json['watchListId'] == null ? undefined : json['watchListId'],
        'entryPrice': json['entryPrice'] == null ? undefined : json['entryPrice'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function WatchListItemCreateDtoToJSON(json: any): WatchListItemCreateDto {
    return WatchListItemCreateDtoToJSONTyped(json, false);
}

export function WatchListItemCreateDtoToJSONTyped(value?: WatchListItemCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stockId': value['stockId'],
        'watchListId': value['watchListId'],
        'entryPrice': value['entryPrice'],
        'note': value['note'],
    };
}

