// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManager.DataContext.Context;

#nullable disable

namespace StockManager.DataContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029082107_StockDataUpdate")]
    partial class StockDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("StockManager.DataContext.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProfitLoss")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AveragePurchasePrice")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MarketCap")
                        .HasColumnType("REAL");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Sector")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ShareOutstanding")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.StockData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Beta")
                        .HasColumnType("REAL");

                    b.Property<double>("CashFlowPerShareTTM")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentDividendYieldTTM")
                        .HasColumnType("REAL");

                    b.Property<double>("DividendPerShareTTM")
                        .HasColumnType("REAL");

                    b.Property<double>("EpsTTM")
                        .HasColumnType("REAL");

                    b.Property<double>("PETTM")
                        .HasColumnType("REAL");

                    b.Property<double>("PSTTM")
                        .HasColumnType("REAL");

                    b.Property<double>("PriceToBookvalue")
                        .HasColumnType("REAL");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TenDayAverageTradingVolume")
                        .HasColumnType("REAL");

                    b.Property<double>("ThreeMonthAverageTradingVolume")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("YearHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("YearLow")
                        .HasColumnType("REAL");

                    b.Property<double>("longTermDebtToEquityAnnual")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("StockData");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.StockReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcceptedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FiledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quarter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockReports");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.StockReportItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportSection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StockReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StockReportId");

                    b.ToTable("StockReportItems");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Fee")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PortfolioItemId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioItemId");

                    b.HasIndex("StockId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.WatchListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("WatchListId");

                    b.ToTable("WatchListItems");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.Portfolio", b =>
                {
                    b.HasOne("StockManager.DataContext.Entities.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.PortfolioItem", b =>
                {
                    b.HasOne("StockManager.DataContext.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.DataContext.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.StockData", b =>
                {
                    b.HasOne("StockManager.DataContext.Entities.Stock", "Stock")
                        .WithOne("StockData")
                        .HasForeignKey("StockManager.DataContext.Entities.StockData", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.StockReport", b =>
                {
                    b.HasOne("StockManager.DataContext.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.StockReportItem", b =>
                {
                    b.HasOne("StockManager.DataContext.Entities.StockReport", "StockReport")
                        .WithMany("StockReportItems")
                        .HasForeignKey("StockReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockReport");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.Transaction", b =>
                {
                    b.HasOne("StockManager.DataContext.Entities.PortfolioItem", "PortfolioItem")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.DataContext.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioItem");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.WatchList", b =>
                {
                    b.HasOne("StockManager.DataContext.Entities.User", "User")
                        .WithOne("WatchList")
                        .HasForeignKey("StockManager.DataContext.Entities.WatchList", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.WatchListItem", b =>
                {
                    b.HasOne("StockManager.DataContext.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.DataContext.Entities.WatchList", "WatchList")
                        .WithMany("WatchListItems")
                        .HasForeignKey("WatchListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.Portfolio", b =>
                {
                    b.Navigation("PortfolioItems");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.PortfolioItem", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.Stock", b =>
                {
                    b.Navigation("StockData")
                        .IsRequired();
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.StockReport", b =>
                {
                    b.Navigation("StockReportItems");
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.User", b =>
                {
                    b.Navigation("Portfolios");

                    b.Navigation("WatchList")
                        .IsRequired();
                });

            modelBuilder.Entity("StockManager.DataContext.Entities.WatchList", b =>
                {
                    b.Navigation("WatchListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
